# Generated by Django 4.1.6 on 2023-02-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_created_task_important_task_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datecomplete',
            field=models.DateTimeField(null=True),
        ),
    ]
