# Generated by Django 4.1.6 on 2023-02-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_datecomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datecomplete',
            new_name='datecompleted',
        ),
    ]
